export const HttpResponse = {
    SERVER_ERROR: "Internal server error",
    USER_EXIST: "User already exist",
    PAGE_NOT_FOUND: "Route not found",
    USER_NOT_FOUND: "User not found",
    PASSWORD_INCORRECT: "Incorrect password, try again",
    NO_TOKEN: "Token not provided",
    OTP_INCORRECT: "Incorrect otp, try again",
    OTP_NOT_FOUND: "Otp not found",
    INCORRECT_OTP: "Incorrect OTP",
    OTP_VERIFIED: 'OTP verified',
    INVALID_CREDENTIALS: "Invalid credentials",
    INVALID_PASSWORD: "Invalid password",
    USER_CREATION_FAILED: "User creation failed",
    USER_CREATION_SUCCESS: "User created successfully",
    UNEXPECTED_KEY_FOUND: "Unexpected key found",
    INVALID_EMAIL: "Invalid email address",
    RESET_PASS_LINK: "Link for resetting password is sended to email",
    TOKEN_EXPIRED: "Token not valid or expired!",
    PASSWORD_CHANGE_SUCCESS: "Password changed successfully!",
    UNAUTHORIZED: "Unauthorized access!",
    SUCCESS_REGISTER: "Registered successfully",
    ADMIN_ALREADY_EXIST: "Admin already exists",
    ADMIN_NOT_FOUND: "Admin not found",
    USER_FETCH_SUCCESS: "User fetched successfully",
    UNABLE_FETCH_USERS: "Unable to fetch users",
    RECRUITER_FETCH_SUCCESS: 'Recruiter fetched successfully',
    UNABLE_FETCH_RECRUITERS: 'Unable to fetch recruiters',
    INVALID_REQUEST_DATA: 'Invalid request data',
    USER_STATUS_UPDATE_SUCCESS: "User status updated successfully",
    USER_STATUS_UPDATE_FAIL: "Failed to update user status",
    RECRUITER_STATUS_UPDATE_SUCCESS: "Recruiter status updated successfully",
    RECRUITER_NOT_FOUND: "Recruiter not found",
    RECRUITER_STATUS_UPDATE_FAIL: "Failed to update recruiter status",
    JOB_POST_SUCCESS: 'Job Posted Successfully',
    RETRIVE_JOBS_SUCCESS: 'successfully retrived jobs',
    JOB_DELETE_SUCCESS: 'job deleted successfully',
    JOBS_FETCH_SUCCESS: 'Jobs fetched successfully',
    OTP_SENT_EMAIL: 'OTP has been sented to your email.',
    OTP_EXPIRED_OR_IVALID: "OTP expired or invalid",
    USER_BLOCKED: 'User is blocked',
    PASSWORD_RESET_SUCCESS: 'Password Reset Success',
    USER_LOGIN_SUCCESS: 'User login success',
    RECRUITER_ALREADY_EXIST: "Recruiter already exists",
    RECRUITER_CREATE_SUCCESS: 'Recruiter created successfully',
    RECRUITER_BLOCK: 'Recruiter is blocked',
    RECRUITER_LOGIN_SUCCESS: 'Recruiter login success',
    UNKNOWN_ERROR: "An unknown error occurred:",
    FAIL_UPDATE_USER_STATUS: "Failed to update user status",
    FAIL_UPDATE_RECRUITER_STATUS: "Failed to update recruiter status",
    INVALID_GOOGLE_TOKEN: "Invalid Google token",
    GOOGLE_AUTH_FAIL: "Google authentication failed",
    UNABLE_FETCH_JOBS: 'Unable to fetch Jobs',
    OTP_SENT_SUCCESS: "OTP sent successfully",
    OTP_VERIFY_SUCCESS: "OTP verified successfully",
    APPLY_SUCCESS: 'Job applied successfully',
    USER_EDIT_SUCCESS: 'User updated succesfull',
    RECRUITER_EDIT_SUCCESS: 'Recruiter updated succesfull',
    JOB_NOT_FOUND: 'Job not found',
    JOB_EDIT_SUCCESS: 'Job edited successfully',
    EXPEREIENCE_ADD_SUCCESS: 'Expereince addedd successfully',
    CANNOT_ADD_EXPERIENCE: 'Cannot add experience',
    EXPEREIENCE_GET_SUCCESS: 'Expereince get successfully',
    CANNOT_GET_EXPERIENCE: 'Cannot get experience',
    EXPEREIENCE_DELETE_SUCCESS: 'Expereince delete successfully',
    EDUCATION_ADD_SUCCESS: 'Education add successfully',
    EDUCATION_GET_SUCCESS: 'Education get successfully',
    EDUCATON_DELETE_SUCCESS: 'Education delete successfully',
    CANNOT_ADD_EDUCATION: 'Cannot add education',
    CANNOT_EDIT_EDUCATION: 'Cannot edit education',
    CANNOT_GET_EDUCATION: 'Cannot get education',
    CATEGORY_ADD_SUCCESS: 'Category add successfully',
    ERROR_ADD_CATEGORY: 'Error adding category',
    SKILLS_GET_SUCCESS: 'Skills get successfully',
    CATEGORY_ALREADY_EXIST: 'Category already exists',
    SKILLS_ADD_SUCCESS: 'Skills add successfully'
}