export const HttpResponse = {
    SERVER_ERROR: "Internal server error",
    USER_EXIST: "User already exist",
    PAGE_NOT_FOUND: "Route not found",
    USER_NOT_FOUND: "User not found",
    PASSWORD_INCORRECT: "Incorrect password, try again",
    NO_TOKEN: "Token not provided",
    OTP_INCORRECT: "Incorrect otp, try again",
    OTP_NOT_FOUND: "Otp not found",
    INCORRECT_OTP: "Incorrect OTP",
    OTP_VERIFIED: 'OTP verified',
    INVALID_CREDENTIALS: "Invalid credentials",
    INVALID_PASSWORD: "Invalid password",
    USER_CREATION_FAILED: "User creation failed",
    USER_CREATION_SUCCESS: "User created successfully",
    UNEXPECTED_KEY_FOUND: "Unexpected key found",
    INVALID_EMAIL: "Invalid email address",
    RESET_PASS_LINK: "Link for resetting password is sended to email",
    TOKEN_EXPIRED: "Token not valid or expired!",
    PASSWORD_CHANGE_SUCCESS: "Password changed successfully!",
    UNAUTHORIZED: "Unauthorized access!",
    SUCCESS_REGISTER: "Registered successfully",
    ADMIN_ALREADY_EXIST: "Admin already exists",
    ADMIN_NOT_FOUND: "Admin not found",
    USER_FETCH_SUCCESS: "User fetched successfully",
    UNABLE_FETCH_USERS: "Unable to fetch users",
    RECRUITER_FETCH_SUCCESS: 'Recruiter fetched successfully',
    UNABLE_FETCH_RECRUITERS: 'Unable to fetch recruiters',
    INVALID_REQUEST_DATA: 'Invalid request data',
    USER_STATUS_UPDATE_SUCCESS: "User status updated successfully",
    USER_STATUS_UPDATE_FAIL: "Failed to update user status",
    RECRUITER_STATUS_UPDATE_SUCCESS: "Recruiter status updated successfully",
    RECRUITER_NOT_FOUND: "Recruiter not found",
    RECRUITER_STATUS_UPDATE_FAIL: "Failed to update recruiter status",
    JOB_POST_SUCCESS: 'Job Posted Successfully',
    RETRIVE_JOBS_SUCCESS: 'successfully retrived jobs',
    JOB_DELETE_SUCCESS: 'job deleted successfully',
    JOBS_FETCH_SUCCESS: 'Jobs fetched successfully',
    OTP_SENT_EMAIL: 'OTP has been sented to your email.',
    OTP_EXPIRED_OR_IVALID: "OTP expired or invalid",
    USER_BLOCKED: 'User is blocked',
    PASSWORD_RESET_SUCCESS: 'Password Reset Success',
    USER_LOGIN_SUCCESS: 'User login success',
    RECRUITER_ALREADY_EXIST: "Recruiter already exists",
    RECRUITER_CREATE_SUCCESS: 'Recruiter created successfully',
    RECRUITER_BLOCK: 'Recruiter is blocked',
    RECRUITER_LOGIN_SUCCESS: 'Recruiter login success',
    UNKNOWN_ERROR: "An unknown error occurred:",
    FAIL_UPDATE_USER_STATUS: "Failed to update user status",
    FAIL_UPDATE_RECRUITER_STATUS: "Failed to update recruiter status",
    INVALID_GOOGLE_TOKEN: "Invalid Google token",
    GOOGLE_AUTH_FAIL: "Google authentication failed",
    UNABLE_FETCH_JOBS: 'Unable to fetch Jobs',
    OTP_SENT_SUCCESS: "OTP sent successfully",
    OTP_VERIFY_SUCCESS: "OTP verified successfully",
    APPLY_SUCCESS: 'Job applied successfully',
    USER_EDIT_SUCCESS: 'User updated succesfull',
    RECRUITER_EDIT_SUCCESS: 'Recruiter updated succesfull',
    JOB_NOT_FOUND: 'Job not found',
    JOB_EDIT_SUCCESS: 'Job edited successfully',
    EXPEREIENCE_ADD_SUCCESS: 'Expereince addedd successfully',
    CANNOT_ADD_EXPERIENCE: 'Cannot add experience',
    EXPEREIENCE_GET_SUCCESS: 'Expereince get successfully',
    CANNOT_GET_EXPERIENCE: 'Cannot get experience',
    EXPEREIENCE_DELETE_SUCCESS: 'Expereince delete successfully',
    EDUCATION_ADD_SUCCESS: 'Education add successfully',
    EDUCATION_GET_SUCCESS: 'Education get successfully',
    EDUCATON_DELETE_SUCCESS: 'Education delete successfully',
    CANNOT_ADD_EDUCATION: 'Cannot add education',
    CANNOT_EDIT_EDUCATION: 'Cannot edit education',
    CANNOT_GET_EDUCATION: 'Cannot get education',
    CATEGORY_ADD_SUCCESS: 'Category add successfully',
    ERROR_ADD_CATEGORY: 'Error adding category',
    SKILLS_GET_SUCCESS: 'Skills get successfully',
    CATEGORY_ALREADY_EXIST: 'Category already exists',
    SKILLS_ADD_SUCCESS: 'Skills add successfully',
    APPLICANTS_GET_SUCCESS: 'Applicants get successfully',
    GET_FAIL: 'Failure on getting.',
    SPAM_CREATE_SUCCESS:'Your report has been submitted successfully. Our team will review it shortly.',
    REPORT_GET_SUCCESS: 'reports get successfully',
    DOWNLOAD_SUCCESS: 'Download success',
    INTERVIEW_SHEDULE_SUCCUSS: 'interview successfully sheduled',
    INTERVIEW_GET_SUCCESS: 'interviews get successfully',
    NOTIFICATION_GET_SUCCESS: 'notifications get successfully',
    NOTIFICATION_DELETE_SUCCESS: 'notification deleted successfully',
    ALREADY_SHEDULED_INTERVIEW: 'An interview already exists at this time on this date.',
    GET_SPAMMER_SUCCESSFULL: 'spammer get successfully',
    ADMIN_DASHBOARD_GET_SUCCESS: 'admin dashboard get successfully',
    GET_COMPANIES_SUCESS: 'companies get successfully',
    RATING_ADD_SUCCESS: 'rating added successfully',
    RATING_GET_SUCCESS: 'rating getting successfully',
    RECRUITER_DASHBOARD_GET_SUCCESS: 'dashboard getting successfully',
    PREMIUM_PURCHASE_SUCCESS: 'purchase created successfully',
    INTERVIEW_GET_FAIL: 'interview get failed',
    OFFERLETTER_POST_SUCCESS: 'offer letter added successfully',
    OFFERLETTER_PASSWORD_VERIFIED: 'offer letter password verified',
    DAILY_VISIT_COUNT_GET_FAIL: 'getting daily visit count failed',
    DAILY_ADD_JOB_COUNT_GET_FAIL: 'getting daily add job count failed',
    FEEDBACK_GET_SUCCESS: 'feedback get successully',
    FEEDBACK_ADD_SUCCESS: 'feedback add successfully',
    FEEDBACK_NOT_FOUND: 'feedbacks not found',
    CATEGORY_GET_SUCCESS: 'categories get successfully',
    CATEGORY_GET_FAIL: 'category get failed',
    CATEGORY_DELETE_SUCCESS: 'category delete success',
    JOBROLES_DELETE_SUCCESS: 'jobrole deleted successfully',
    DECLINE_MAIL_SENT: 'decline mail has been sented successfully',
    INTERVIEW_RESHEDULED: 'interview resheduled successfully',
    APPLICATION_HIRED_SUCCESS: 'applicant hired successfully',
    PREMIUM_GET_SUCCESS: 'premium get successfully',
    PREMIUM_CREATE_SUCCESS: 'premium created successfully',
    PREMIUM_UPDATE_SUCCESS: 'premium updated successfully',
    PREMIUM_DELETE_SUCCESS: 'premium deleted successfully',
    PREMIUM_FET_FAIL: 'premium get failed'
}